source "http://rubygems.org"

gemspec

gem 'refinerycms', :git => 'git://github.com/keram-refinery/refinerycms.git', :branch => 'refinery_light'
gem 'refinerycms-i18n', :git => 'git://github.com/keram-refinery/refinerycms-i18n.git', :branch => 'refinery_light'

# Database Configuration
platforms :jruby do
  gem 'activerecord-jdbcsqlite3-adapter'
  gem 'activerecord-jdbcmysql-adapter'
  gem 'activerecord-jdbcpostgresql-adapter'
  gem 'jruby-openssl'
end

platforms :ruby do
  gem 'sqlite3'
  gem 'mysql2'
  gem 'pg'
end

group :development, :test do
  gem 'refinerycms-testing'#, :git => 'git://github.com/refinery/refinerycms.git'

  platforms :ruby do
    require 'rbconfig'
    if RbConfig::CONFIG['target_os'] =~ /linux/i
      gem 'therubyracer', '~> 0.11.4'
    end
  end
end

# Gems used only for assets and not required
# in production environments by default.
gem 'sass-rails', '~> 4.0.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'uglifier'

gem 'turbolinks', '~> 2.0.0'

gem 'jquery-rails', '~> 3.0.4'
gem 'jquery-ui-rails', '~> 4.0.4'
